apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://code.almond.eu/tools/aks-apps.git
      path: apps-shared-tools/argocd-extra/
      targetRevision: almond-logo
      
    - repoURL: https://argoproj.github.io/argo-helm
      targetRevision: 8.0.17
      chart: argo-cd
      helm:
        values: |
          applicationSet:
            replicas: 1
          controller:
            replicas: 1
          dex:
            enabled: false
          redis-ha:
            enabled: false
          server:
            replicas: 1
            service:
              annotations:
                service.beta.kubernetes.io/azure-load-balancer-internal: "true"
              type: LoadBalancer
            volumes:
              - name: svg-logo
                configMap:
                  name: svg-logo-cm

            volumeMounts:
              - name: svg-logo
                mountPath: /shared/app/assets/images/logo.svg
                subPath: logo.svg
                readOnly: true

          configs:
            styles: |
              .login__logo.width-control::after {
                content: "";
                display: block;
                width: 150px;
                height: 150px;
                background-image: url(/assets/images/logo.svg);
                background-size: contain;
                background-repeat: no-repeat;
                background-position: center;
                margin: 0 auto;
              }
            cm:
              accounts.keep: apiKey
              # url: __REPLACE_THIS__OR_REMOVE__
              # admin.enabled: true
              # oidc.config: |
              #   name: Azure
              #   issuer: https://login.microsoftonline.com/__REPLACE_THIS__/v2.0
              #   clientID: __REPLACE_THIS__
              #   clientSecret: $oidc.azure.clientSecret
              #   requestedIDTokenClaims:
              #     groups:
              #       essential: true
              #   requestedScopes:
              #     - openid
              #     - profile
              #     - email
              # rbac:
              #   policy.csv: |
              #     g, "__REPLACE_THIS__", role:admin
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
