apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.podName }}
  labels:
    app: {{ .Values.podName }}
spec:
  containers:
    - name: {{ .Values.podName }}
      image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
      imagePullPolicy: {{ .Values.image.pullPolicy }}
      ports:
        - containerPort: 80